credentials:
  usernames:
    kkeough:
      email: kyle.keough@allcloud.io
      name: Kyle Keough
      password: '$2b$12$hbqIiMHZcg74EnHdlehTquBKzuYuLpgL8uIWIOPu2Bl/VjgyFOV7q'
cookie:
  expiry_days: 30
  key: 'password-rand-string-key'
  name: random_cookie_name
